[build]
publish = "public"
command = "sh build.sh"
[context.production.environment]
HUGO_VERSION = "0.89.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.split1]
command = "sh build.sh --enableGitInfo"
[context.split1.environment]
HUGO_VERSION = "0.89.4"
HUGO_ENV = "production"
[context.deploy-preview]
command = "sh build.sh --buildFuture -b $DEPLOY_PRIME_URL/blog/"
[context.deploy-preview.environment]
HUGO_VERSION = "0.89.4"
[context.branch-deploy]
command = "sh build.sh -b $DEPLOY_PRIME_URL/blog/"
[context.branch-deploy.environment]
HUGO_VERSION = "0.89.4"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
